# Generated by Django 3.2.7 on 2022-03-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_verificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtoken',
            name='value',
            field=models.CharField(max_length=60),
        ),
    ]
