# Generated by Django 3.2.7 on 2022-03-14 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_verificationtoken_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationtoken',
            name='user',
        ),
        migrations.AddField(
            model_name='verificationtoken',
            name='profile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
