# Generated by Django 3.2.7 on 2022-03-24 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220314_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtoken',
            name='owner_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
