# Generated by Django 3.2.7 on 2022-03-24 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_verificationtoken_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationtoken',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='verificationtoken',
            name='token_uuid',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
    ]
