# Generated by Django 3.2.7 on 2022-03-28 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_requestpassworduuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpassworduuid',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
