# Generated by Django 3.2.7 on 2022-03-28 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_requestpassworduuid_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestpassworduuid',
            name='owner',
        ),
        migrations.AddField(
            model_name='requestpassworduuid',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
