# Generated by Django 3.2.7 on 2022-03-28 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0014_auto_20220328_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpassworduuid',
            name='owner',
            field=models.ManyToManyField(related_name='password_request_uuid', to=settings.AUTH_USER_MODEL),
        ),
    ]
