# Generated by Django 3.2.7 on 2022-03-28 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0015_alter_requestpassworduuid_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestpassworduuid',
            name='owner',
        ),
        migrations.AddField(
            model_name='requestpassworduuid',
            name='owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
